[build]
publish = "."
functions = "netlify/functions"

# Don’t cache HTML
[[headers]]
for = "/"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

# Routes
[[redirects]]
from = "/api/game"
to = "/.netlify/functions/game"
status = 200

[[redirects]]
from = "/api/state"
to = "/.netlify/functions/state"
status = 200

[[redirects]]
from = "/api/tap"
to = "/.netlify/functions/tap"
status = 200

[[redirects]]
from = "/api/confirmTap"
to = "/.netlify/functions/confirmTap"
status = 200

[[redirects]]
from = "/api/prepareReveal"
to = "/.netlify/functions/prepareReveal"
status = 200

[[redirects]]
from = "/api/confirmReveal"
to = "/.netlify/functions/confirmReveal"
status = 200
