[build]
publish = "."
functions = "netlify/functions"

# Optional caching rules (good for your HTML refresh issue earlier)
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
