[build]
publish = "."

[functions]
directory = "netlify/functions"

# API routes → functions (no leading "./")
[[redirects]]
from = "/api/game"
to = "/.netlify/functions/game"
status = 200

[[redirects]]
from = "/api/state"
to = "/.netlify/functions/state"
status = 200

[[redirects]]
from = "/api/tap"
to = "/.netlify/functions/tap"
status = 200

[[redirects]]
from = "/api/confirm-tap"
to = "/.netlify/functions/confirmTap"
status = 200

[[redirects]]
from = "/api/prepare-reveal"
to = "/.netlify/functions/prepareReveal"
status = 200

[[redirects]]
from = "/api/confirm-reveal"
to = "/.netlify/functions/confirmReveal"
status = 200

# (Optional) keep HTML uncached by CDN so updates show instantly
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "no-store, max-age=0"
